### ISSUE TITLE
Logged in and not

### ISSUE THREAD

**Issue by daniel-butler-irl** [IBM/deployable-architecture-builder-vscode-extension#6]
**Describe the bug**

I logged in with API key to Goldeneye.Development account. I see login successful popup and it is listed in the bottom bar but it also says I am logged out. 

**Steps to reproduce**
Login with API Key

**Expected behavior**
Expected to be logged in

**Screenshots**
![image](https://github.com/user-attachments/assets/159aea4e-b089-4bd6-821b-e19c3a9e1382)

**Links to DAs, releases, catalog JSONs, input YAMLs, Terraform modules**
If applicable, link to public examples that can be used to reproduce your issue. For example repos, catalog entries, and so on.

**Versions**
 - OS: darwin-arm64
 - Vscode Version (for example v1.62.0): 1.93.1
 - IBM Cloud Deployable Architecture Builder extension version (for example v1.62.0): v1.0.0

**Additional context**

**Comment by daniel-butler-irl** [comment]
After VS Code restart it seems to work. There is still a bug here on first install

**Comment by gee4vee** [comment]
This should be fixed in the 1.0.1 release which is out now. Let us know if you still have issues.
