### ISSUE TITLE
Projects List not paginating correctly

### ISSUE THREAD

**Issue by daniel-butler-irl** [IBM/deployable-architecture-builder-vscode-extension#7]
**Describe the bug**
I have 150+ projects on my dev account for testing. Not all projects are listed in the Projects explorer. I expect it's not paginating correctly, If I were to guess you are not paginating and pulling the max of 100 projects from the API. Covers most people but not me 😉. A search bar would be nice too...

**Steps to reproduce**
Detailed steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Links to DAs, releases, catalog JSONs, input YAMLs, Terraform modules**
If applicable, link to public examples that can be used to reproduce your issue. For example repos, catalog entries, and so on.

**Versions**
 - OS: one of win32-x64, win32-ia32, win32-arm64, linux-x64, linux-arm64, linux-armhf, darwin-x64, darwin-arm64, alpine-x64, alpine-arm64, web
 - Vscode Version (for example v1.62.0):
 - IBM Cloud Deployable Architecture Builder extension version (for example v1.62.0):

**Additional context**

**Comment by gee4vee** [comment]
@daniel-butler-irl So there is a setting for the extension to increase the number of children for the trees. If you go to Settings -> Extensions -> _name of our extension_ -> Max children, you can increase it.

Unfortunately the extension APIs don't seem to provide a way to add a proper search field to explorer tree views. MS seems to reserve that functionality for their own views like the Extension Marketplace view. However, you can [search any tree view](https://code.visualstudio.com/updates/v1_89#_find-in-trees-keybinding) assuming the relevant nodes are expanded. It's not ideal, but that's what's available.

**Comment by daniel-butler-irl** [comment]
Great thanks that worked for me thanks
