### ISSUE TITLE
ibm_catalog.json Incorrect type assertions in flavor->configuration

### ISSUE THREAD

**Issue by daniel-butler-irl** [IBM/deployable-architecture-builder-vscode-extension#8]
**Describe the bug**
Some of the type checking is incorrect. I am seeing warnings for boolean type expected string, and array type expected string

**Steps to reproduce**
set type to boolean, or array. 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/10872534-b8c1-4f0a-bc03-93d1e079a56c)
![image](https://github.com/user-attachments/assets/65019327-0e16-4528-bf9e-87ad38a68bef)

**Links to DAs, releases, catalog JSONs, input YAMLs, Terraform modules**
If applicable, link to public examples that can be used to reproduce your issue. For example repos, catalog entries, and so on.

**Versions**
 - OS: one of win32-x64, win32-ia32, win32-arm64, linux-x64, linux-arm64, linux-armhf, darwin-x64, darwin-arm64, alpine-x64, alpine-arm64, web
 - Vscode Version (for example v1.62.0):
 - IBM Cloud Deployable Architecture Builder extension version (for example v1.62.0):

**Additional context**

**Comment by gee4vee** [comment]
@daniel-butler-irl Can you attach your catalog.json file to reproduce?

**Comment by gee4vee** [comment]
Fix is merged. Since the schema is external, no code changes in the extension are needed. You might have to restart VS Code to pick up the updated schema.
